version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5228:5228" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5228
      - ConnectionStrings__DefaultConnection=Data Source=host.docker.internal;Initial Catalog=burger;
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "sa"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"